Lecture 4 cart
darishenko/phoneshop-servlet-api pull request #5
Opened 2023-05-22 01:23 UTC by darishenko

2023-05-23 00:19 UTC, marharyta-aheyanka requested changes

2023-05-23 00:19 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/CartPageServlet.java
> +            updateCartItem(productIds[i], productQuantities[i], updateCartErrors, request);
try to use IntStream.range instead of loop

2023-05-23 00:19 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +    private int parseQuantityRequestParameter(HttpServletRequest request)
you can create separate service to parse quantity, it will allow to avoid code duplication

2023-05-25 06:30 UTC, alexeyburak commented on src/main/java/com/es/phoneshop/model/cart/service/DefaultQuantityService.java
> +        if(quantityNumber.doubleValue() != quantityNumber.intValue()){
check formatting here and in other classes

2023-05-29 16:21 UTC, merged